enabled = "yes"

[settings]
url_prefix = "/api"
#subdomain = ""
#url_defaults = {}
#static_folder = "static"
#template_folder = "templates"
#static_url_path = "/api/static"

#[session]
#api_session = "yes"

